version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYAPP_DATABASE_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
  redis:
    image: redis:3.2.0-alpine
  app:
    build: .
    volumes:
      - bundle:/bundle
    environment:
      MYAPP_DATABASE_USERNAME: root
      MYAPP_DATABASE_PASSWORD: $MYAPP_DATABASE_PASSWORD
      MYAPP_DATABASE_HOST: db
  web:
    extends:
      service: app
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: /bin/bash -c 'bundle exec rake assets:precompile; script/web-start'
    ports:
      - "13000:3000"
    links:
      - db
      - redis
  worker:
    extends:
      service: app
    #command: bundle exec sidekiq -q notification
    command: script/sidekiq-start
    links:
      - db
      - redis

volumes:
  db-data:
    driver: local
  bundle:
    driver: local
