version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYAPP_DATABASE_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
  redis:
    image: redis:3.2.0-alpine
  app:
    build: .
    volumes:
      - bundle:/bundle
    environment:
      MYAPP_DATABASE_USERNAME: root
      MYAPP_DATABASE_PASSWORD: $MYAPP_DATABASE_PASSWORD
      MYAPP_DATABASE_HOST: db
  web:
    extends:
      service: app
    command: /bin/bash -c 'bundle exec rake assets:precompile; script/web-start'
    ports:
      - "3000"
    environment:
      VIRTUAL_HOST: sandbox.t-taira.org
    links:
      - db
      - redis
  worker:
    extends:
      service: app
    command: script/sidekiq-start
    links:
      - db
      - redis

volumes:
  db-data:
    driver: local
  bundle:
    driver: local
