FROM ruby:2.2.4
ENV LANG C.UTF-8
RUN apt-get update -qq && apt-get install -y build-essential
RUN mkdir /myapp
WORKDIR /myapp

ADD Gemfile Gemfile.lock /myapp/
RUN bundle install --jobs 20 --retry 5 --without development test

ENV RAILS_ENV production
ADD . /myapp
RUN bundle exec rake tmp:create
RUN bundle exec rake assets:precompile
