# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 357eb9ae6fdbaaeb36c81367d6d6db3a8f143b94c6bdcb494cf9ae4e164d354aef5237ff40aecb613b927f32c9ba520082f2fdd52b59a3354220cfc8c33cfd21

test:
  secret_key_base: 70393034293aaa45bf7fa46063f5690cdf43300370314bad4a463f23eeba40f9a0036e15fd18ae6a03c24c8bc4071e0ee8a33f1c5adc3fdd40f831c2efa060de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
